# Explicit local-semantic component installation; no dependency or weight fetch.
# The isolated portrait bundle must also own the shared source-artifact reader.
set(ORCA_LOCAL_SEMANTIC_RUNTIME_FILES
    "${CMAKE_SOURCE_DIR}/tools/ai/glb_artifact.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/beauty_leaf_domain.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_leaf_boundaries.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/portrait_surface_ownership.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/beauty_runtime_manifest.json"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_worker.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_geometry.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_render.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_transform.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_views.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_projection.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_pipeline.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_request.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_eye_landmarks.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_face_landmarks.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_shape_constraints.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_brow_boundary.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_contour_proposals.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_surface_contours.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_leaf_boundaries.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/beauty_leaf_domain.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/portrait_residual_proposal.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/bundled_portrait_runtime.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_body_regions.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_parent_ownership.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_parent_boundary.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_parent_projection.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_hair_expansion_guard.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_region_mask_consensus.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_region_mask_projection.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_surface_region_consensus.py"
    "${CMAKE_SOURCE_DIR}/tools/ai/local_surface_region_holes.py"
)
if(ORCA_AI_PORTRAIT_RECOGNITION)
    list(APPEND ORCA_LOCAL_SEMANTIC_RUNTIME_FILES
        "${CMAKE_SOURCE_DIR}/tools/ai/portrait_parent_cleanup_catalog.json"
        "${CMAKE_SOURCE_DIR}/tools/ai/portrait_parent_cleanup_fangfei.json"
        "${CMAKE_SOURCE_DIR}/tools/ai/portrait_parent_cleanup_partition.json"
        "${CMAKE_SOURCE_DIR}/tools/ai/portrait_parent_cleanup_locks.json")
endif()
