include_guard(GLOBAL)
if(NOT ORCA_AI_RUNTIME_ARCHITECTURE STREQUAL "x64")
    return()
endif()

set(ORCA_AI_NUMPY_VERSION "2.2.6")
set(ORCA_AI_NUMPY_WHEEL_FILENAME "numpy-2.2.6-cp312-cp312-win_amd64.whl")
set(ORCA_AI_NUMPY_WHEEL_URL "https://files.pythonhosted.org/packages/36/fa/8c9210162ca1b88529ab76b41ba02d433fd54fecaf6feb70ef9f124683f1/numpy-2.2.6-cp312-cp312-win_amd64.whl")
set(ORCA_AI_NUMPY_WHEEL_SHA256 "c1f9540be57940698ed329904db803cf7a402f3fc200bfe599334c9bd84a40b2")
set(ORCA_AI_OPENCV_VERSION "4.10.0.84")
set(ORCA_AI_OPENCV_WHEEL_FILENAME "opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl")
set(ORCA_AI_OPENCV_WHEEL_URL "https://files.pythonhosted.org/packages/26/d0/22f68eb23eea053a31655960f133c0be9726c6a881547e6e9e7e2a946c4f/opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl")
set(ORCA_AI_OPENCV_WHEEL_SHA256 "afcf28bd1209dd58810d33defb622b325d3cbe49dcd7a43a902982c33e5fad05")
set(ORCA_AI_WEIGHTS_DIR "" CACHE PATH "Verified local portrait weights for offline packaging")
set(ORCA_AI_PORTRAIT_SITE_PACKAGES "" CACHE PATH "Local CPython 3.12 CPU dependencies to include in the offline package")
if(NOT IS_DIRECTORY "${ORCA_AI_WEIGHTS_DIR}" OR NOT IS_DIRECTORY "${ORCA_AI_PORTRAIT_SITE_PACKAGES}")
    message(FATAL_ERROR "Offline portrait packaging requires verified weights and local CPU site-packages")
endif()

function(orca_portrait_wheel name filename url sha)
    set(wheel "${ORCA_AI_WHEEL_CACHE_DIR}/${filename}")
    if(NOT EXISTS "${wheel}")
        file(DOWNLOAD "${url}" "${wheel}" EXPECTED_HASH "SHA256=${sha}" TLS_VERIFY ON
            STATUS status TIMEOUT 180 INACTIVITY_TIMEOUT 30)
        list(GET status 0 code)
        if(NOT code EQUAL 0)
            message(FATAL_ERROR "Cannot obtain pinned ${name} build dependency")
        endif()
    endif()
    file(SHA256 "${wheel}" actual)
    if(NOT actual STREQUAL sha)
        message(FATAL_ERROR "Pinned ${name} wheel hash changed")
    endif()
    set(ORCA_AI_${name}_WHEEL "${wheel}" PARENT_SCOPE)
endfunction()
orca_portrait_wheel(NUMPY "${ORCA_AI_NUMPY_WHEEL_FILENAME}" "${ORCA_AI_NUMPY_WHEEL_URL}" "${ORCA_AI_NUMPY_WHEEL_SHA256}")
orca_portrait_wheel(OPENCV "${ORCA_AI_OPENCV_WHEEL_FILENAME}" "${ORCA_AI_OPENCV_WHEEL_URL}" "${ORCA_AI_OPENCV_WHEEL_SHA256}")
include("${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_runtime_files.cmake")
set(identity "${ORCA_AI_PORTRAIT_SITE_PACKAGES};${ORCA_AI_WEIGHTS_DIR};${_bundled_python_version}")
set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
include(InstallRequiredSystemLibraries)
get_filename_component(_portrait_deps_build "${CMAKE_PREFIX_PATH}/../../.." ABSOLUTE)
find_file(ORCA_AI_PYTHON_STABLE_ABI_DLL NAMES python3.dll PATHS "${Python3_ROOT_DIR}"
    "${_portrait_deps_build}/dep_python3-prefix/src/dep_python3/PCbuild/amd64" NO_DEFAULT_PATH REQUIRED)
list(APPEND CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS "${ORCA_AI_PYTHON_STABLE_ABI_DLL}")
set(native_args)
foreach(file IN LISTS CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
    file(SHA256 "${file}" sha)
    string(APPEND identity "${sha}")
    list(APPEND native_args --native-file "${file}")
endforeach()
foreach(file IN LISTS ORCA_LOCAL_SEMANTIC_RUNTIME_FILES)
    file(SHA256 "${file}" sha)
    string(APPEND identity "${sha}")
endforeach()
file(SHA256 "${CMAKE_SOURCE_DIR}/tools/ai/stage_bundled_portrait_runtime.py" sha)
string(SHA256 stage_key "${identity}${sha}")
set(ORCA_PORTRAIT_STAGE_DIR "${CMAKE_BINARY_DIR}/_deps/portrait-offline-${stage_key}")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tools/ai/stage_bundled_portrait_runtime.py"
    --base-python "${Python3_ROOT_DIR}" --site-packages "${ORCA_AI_PORTRAIT_SITE_PACKAGES}"
    --weights "${ORCA_AI_WEIGHTS_DIR}" --modules "${CMAKE_SOURCE_DIR}/tools/ai" --destination "${ORCA_PORTRAIT_STAGE_DIR}"
    --wheel "${ORCA_AI_NUMPY_WHEEL}=${ORCA_AI_NUMPY_WHEEL_SHA256}"
    --wheel "${ORCA_AI_OPENCV_WHEEL}=${ORCA_AI_OPENCV_WHEEL_SHA256}"
    --wheel "${ORCA_AI_PILLOW_WHEEL}=${ORCA_AI_PILLOW_WHEEL_SHA256}"
    ${native_args}
    RESULT_VARIABLE staged)
if(NOT staged EQUAL 0)
    message(FATAL_ERROR "Offline portrait runtime staging failed")
endif()
execute_process(COMMAND "${ORCA_PORTRAIT_STAGE_DIR}/python/python.exe" -I
    "${ORCA_PORTRAIT_STAGE_DIR}/modules/bundled_portrait_runtime.py" --root "${ORCA_PORTRAIT_STAGE_DIR}"
    RESULT_VARIABLE verified)
if(NOT verified EQUAL 0)
    message(FATAL_ERROR "Offline portrait runtime isolated imports or hashes failed")
endif()
