if(WIN32)
    set(ORCA_BEAUTY_RASTER_BINARY "" CACHE FILEPATH "Verified offline raster binary for preserved Beauty evidence")
    set(ORCA_BEAUTY_RASTER_SHA256 "" CACHE STRING "SHA256 of the preserved offline raster binary")
    if(ORCA_BEAUTY_RASTER_BINARY)
        if(NOT EXISTS "${ORCA_BEAUTY_RASTER_BINARY}" OR NOT ORCA_BEAUTY_RASTER_SHA256)
            message(FATAL_ERROR "A preserved Beauty raster binary requires its SHA256")
        endif()
        file(SHA256 "${ORCA_BEAUTY_RASTER_BINARY}" raster_hash)
        if(NOT raster_hash STREQUAL ORCA_BEAUTY_RASTER_SHA256)
            message(FATAL_ERROR "Preserved Beauty raster binary identity changed")
        endif()
        install(FILES "${ORCA_BEAUTY_RASTER_BINARY}" DESTINATION "./resources/tools/ai" RENAME "local_semantic_raster.dll")
    else()
        add_library(orca_semantic_raster SHARED "${CMAKE_SOURCE_DIR}/tools/ai/local_semantic_raster.cpp")
        set_target_properties(orca_semantic_raster PROPERTIES OUTPUT_NAME "local_semantic_raster")
        target_compile_features(orca_semantic_raster PRIVATE cxx_std_17)
        if(TARGET OrcaSlicer_app_gui)
            add_dependencies(OrcaSlicer_app_gui orca_semantic_raster)
        endif()
        install(TARGETS orca_semantic_raster RUNTIME DESTINATION "./resources/tools/ai")
    endif()
endif()

set(ORCA_BEAUTY_RUNTIME_ROOT "" CACHE PATH "Prepared portable beauty recognition runtime (no downloads)")
if(ORCA_BEAUTY_RUNTIME_ROOT AND ORCA_AI_PORTRAIT_RECOGNITION)
    if(NOT EXISTS "${ORCA_BEAUTY_RUNTIME_ROOT}/runtime-manifest.json" OR
       NOT EXISTS "${ORCA_BEAUTY_RUNTIME_ROOT}/python/python.exe")
        message(FATAL_ERROR "Incomplete portable beauty runtime")
    endif()
    install(DIRECTORY "${ORCA_BEAUTY_RUNTIME_ROOT}/" DESTINATION "./resources/beauty-runtime"
        PATTERN "__pycache__" EXCLUDE PATTERN "*.pyc" EXCLUDE)
endif()
