# Assemble the redesigned workflows on the existing native GUI target.
set(ORCA_REDESIGN_WORKFLOW_SOURCES
    GUI/AI/ModelGeneration/ModelGenerationAssetsView.cpp
    GUI/AI/SmartSlicing/SmartSlicingPanel.cpp
    GUI/AI/SmartSlicing/SmartSlicingPanel.hpp
    GUI/AI/SmartSlicing/SmartSlicingPresenter.cpp
    GUI/AI/SmartSlicing/SmartSlicingPresenter.hpp
    GUI/AI/SmartSlicing/SmartSlicingViewModel.cpp
    GUI/AI/SmartSlicing/SmartSlicingViewModel.hpp
    GUI/AI/Model/VertexColorRegionEditor.cpp GUI/AI/Model/ModelFinishing.cpp GUI/AI/ModelGeneration/ModelGenerationBeautyView.cpp GUI/AI/Model/BeautySurface.cpp GUI/AI/Model/BeautyAppearance.cpp GUI/AI/Model/BeautyFinishing.cpp GUI/AI/ModelGeneration/BeautyWorkbenchControls.cpp GUI/AI/ModelGeneration/BeautyGuidanceProtectedRegions.cpp GUI/AI/ModelGeneration/BeautyGuidanceProtectedRegions.hpp
    GUI/AI/ModelGeneration/PostGenerationWorkbenchView.cpp
    GUI/AI/ModelGeneration/PostGenerationWorkbenchPresentation.cpp
    GUI/AI/ModelGeneration/PostGenerationWorkbenchHost.cpp
    GUI/AI/ModelGeneration/PostGenerationWorkbenchPalette.cpp
    GUI/AI/ModelGeneration/PostGenerationWorkbenchCheck.cpp
    GUI/AI/ModelGeneration/ModelGenerationBeautySession.cpp
    GUI/AI/ModelGeneration/ModelGenerationBeautyPreview.cpp
    GUI/AI/ModelGeneration/ModelGenerationBeautyExport.cpp
    GUI/AI/ModelGeneration/ModelGenerationBeautyVersions.cpp
    GUI/AI/ModelGeneration/ModelGenerationWorkbenchHistory.cpp
    GUI/AI/ModelGeneration/ModelPreviewSemantics.cpp
    GUI/AI/ModelGeneration/ModelSemanticColoring.cpp
    GUI/AI/ColorMatching/LocalPrintColorPanel.cpp GUI/AI/ModelGeneration/LocalSemanticWorkerClient.cpp GUI/AI/ModelGeneration/ModelGenerationPreviewLayout.cpp GUI/AI/ModelGeneration/ModelGenerationSubmission.cpp
    GUI/AI/Model/VertexColorRegionEditor.hpp GUI/AI/Model/ModelArtifact.cpp GUI/AI/Model/ModelArtifact.hpp GUI/AI/Model/GlbGeometryEditing.cpp GUI/AI/ModelGeneration/ModelGenerationLocalImport.cpp
    GUI/Redesign/RedesignCommand.cpp
    GUI/Redesign/RedesignCommand.hpp
    GUI/Redesign/RedesignFeatureFlags.cpp
    GUI/Redesign/RedesignFeatureFlags.hpp
    GUI/Redesign/OrcaBusinessAdapter.cpp
    GUI/Redesign/OrcaBusinessAdapter.hpp
    GUI/Redesign/RedesignMessageDialog.cpp
    GUI/Redesign/RedesignMessageDialog.hpp
    GUI/Redesign/ImageHistorySidebar.cpp
    GUI/Redesign/ImageHistorySidebar.hpp
    GUI/Redesign/ImageHistoryPagination.hpp
    GUI/Redesign/RedesignModelRoute.hpp
    GUI/Redesign/RedesignShell.cpp
    GUI/Redesign/RedesignModelWorkflow.cpp
    GUI/Redesign/RedesignShell.hpp
    GUI/Redesign/RedesignState.cpp
    GUI/Redesign/RedesignState.hpp
    GUI/Redesign/RedesignTheme.hpp
    GUI/Redesign/StartupSetupService.cpp
    GUI/Redesign/StartupSetupService.hpp
    GUI/Redesign/StartupSetupDialog.cpp
    GUI/Redesign/StartupSetupDialog.hpp
    GUI/Redesign/StartupSplashView.hpp
    GUI/Redesign/StartupBufferView.hpp
    GUI/FilamentColourPalette.hpp
    GUI/Redesign/RedesignWidgets.hpp
    GUI/Redesign/PrinterWorkspaceState.hpp
    GUI/Redesign/OrcaPrinterAdapter.cpp
    GUI/Redesign/OrcaPrinterAdapter.hpp
    GUI/Redesign/PrinterWorkspace.cpp
    GUI/Redesign/PrinterWorkspace.hpp
)
